version: "3.5"

services:

  db:
    image: mysql
    volumes:
      - ./db/seed/:/docker-entrypoint-initdb.d/
    environment:
      MYSQL_USER: username
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3306:3306

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
